# site name
prefixName: ğŸ¦‹
siteName: æ–­æ¡¥ã®çƒŸé›¨
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/custom/avatar.jpg
url: https://zfq0620.gitee.io
description: ä¸€ä¸‡å¹´å¤ªä¹…ä¹‹äº‰æœå¤•ï¼
cdn: https://cdn.jsdelivr.net/gh/zfq0620/cdn@v1.1
pjax: 1
# 1å¼€å¯
mathjax: 0

notice: æ¬¢è¿æ¥åˆ°æ–­æ¡¥çƒŸé›¨çš„åšå®¢
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  é¦–é¡µ: { path: /, fa: fa-fort-awesome faa-shake }
  
  å½’æ¡£: { path: /archives, fa: fa-archive faa-vertical, submenus: {  
    æ ‡ç­¾: {path: /tags/, fa: fa-tags faa-pulse},
    æŠ€æœ¯: {path: /categories/æŠ€æœ¯/, fa: fa-code },
    ç”Ÿæ´»: {path: /categories/ç”Ÿæ´»/, fa: fa-file-text-o }, 
    èµ„æº: {path: /categories/èµ„æº/, fa: fa-cloud-download }, 
    éšæƒ³: {path: /categories/éšæƒ³/, fa: fa-commenting-o }
  } }
  
  æ¸…å•: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    è¯´è¯´: {path: /shuoshuo/, fa: fa-commenting-o fa-commenting },
    ä¹¦å•: {path: /tags/æ‚¦è¯»/, fa: fa-th-list faa-bounce }, 
    ç•ªç»„: {path: /bangumi/, fa: fa-film faa-vertical }, 
    æ­Œå•: {path: /music/, fa: fa-headphones faa-bounce },
    ç›¸å†Œ: {path: /photos/, fa: fa-photo faa-vertical }
  } }
  
  å®éªŒ: { path: /lab/, fa: fa-flask faa-shake }
  ç•™è¨€æ¿: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  å‹äººå¸: { path: /links/, fa: fa-link faa-shake }
  èµèµ: { path: /donate/, fa: fa-heartbeat faa-tada }

  å…³äº: { path: javascript:;, fa: fa-vcard faa-tada, submenus: {
    æˆ‘çš„: {path: /about/, fa: fa-user faa-tada},
    è½¯ä»¶: {path: /android/, fa: fa-android faa-pulse}
  } }

  RSS: { path: /atom.xml, fa: fa-rss faa-vertical }

  
# Home page sort type: -1: newer firstï¼Œ1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# èƒŒæ™¯å›¾ç‰‡ æ›´å¥½çš„ä¿®æ”¹
bgn: 8
bg:
  - https://cdn.jsdelivr.net/gh/zfq0620/PicGo/myphoto/20200330094109.png
  - https://cdn.jsdelivr.net/gh/zfq0620/PicGo/myphoto/173920-151929236017be.jpg
  - https://cdn.jsdelivr.net/gh/zfq0620/PicGo/myphoto/20200330094002.png
  - https://cdn.jsdelivr.net/gh/zfq0620/PicGo/myphoto/20200330095543.png
  - https://cdn.jsdelivr.net/gh/zfq0620/PicGo/myphoto/20200330100216.png
  - https://cdn.jsdelivr.net/gh/yremp/cdn@2.1.5/img/cover/(6).jpg.webp
  - https://cdn.jsdelivr.net/gh/yremp/cdn@2.1.5/img/cover/(8).jpg.webp
  - https://cdn.jsdelivr.net/gh/zfq0620/PicGo/myphoto/20200330094259.png

# èƒŒæ™¯å›¾ç‰‡æ ·å¼ ç©º åŸå›¾æ•ˆæœ filter-dim é˜´å½± filter-grid æ¨ªæ¡ filter-dot ç‚¹ç‚¹
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: http://zfq0620.gitee.io/love, title: çˆ±å¿ƒæ ‘, desc: ä¸ƒå¤•ç§ä¸‹çš„çˆ±å¿ƒæ ‘, img: /img/startdash/sakura.png}
  - {url: https://space.bilibili.com/483624233, title: Bilibili, desc: åšä¸»çš„bç«™è§†é¢‘, img: /img/startdash/bilibili.jpg}
  - {url: https://blog.csdn.net/weixin_45631738, title: æ–­æ¡¥çƒŸé›¨çš„CSDN, desc: æŠ€æœ¯æœåŠ¡, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 02/28/2020

#social  url, img PCç«¯é…ç½®
social:
  github: {url: https://gitee.com/zfq0620, img: /img/social/github.png}
  sina: {url: https://gitee.com/zfq0620, img: /img/social/sina.png}
  wangyiyun: {url: https://gitee.com/zfq0620, img: /img/social/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/zfq0620, img: /img/social/zhihu.png}
  email: {url: https://gitee.com/zfq0620, img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/custom/weixing.png, img: /img/social/wechat.png}

#social  url, img ç§»åŠ¨ç«¯é…ç½®
msocial:
  github: {url: https://gitee.com/zfq0620, fa: fa-github, color: 333}
  weibo: {url: https://weibo.com/u/6381711951/home?leftnav=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=18391763855&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal:  https://cdn.jsdelivr.net/gh/zfq0620/cdn@v1.1
  alipay: /img/custom/alipay.jpg
  wechat: /img/custom/wechat.png
  wechatSQ: /img/custom/weixing.png

# è§†é¢‘åœ°å€ä¸ºhttps://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4ï¼Œé…ç½®å¦‚ä¸‹
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # å¤šä¸ªè§†é¢‘ç”¨é€—å·éš”å¼€ï¼Œéšæœºè·å–ã€‚æ”¯æŒçš„æ ¼å¼ç›®å‰å·²çŸ¥MP4,Flvã€‚å…¶ä»–çš„å¯ä»¥è¯•ä¸‹ï¼Œä¸ä¿è¯æœ‰ç”¨
  name: Unbroken.mp4

aplayer: 
  id: 4887733040
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: none
  volume: 0.7
  mutex: true


# Online contact ##åœ¨çº¿èŠå¤©
daovoice: true
daovoice_app_id: f07007f7 ##è¿™é‡Œæ›¿æ¢æˆä½ DaoVoiceä¸Šçš„appid

#2dæ¿å¨˜
# Live2D
## https://github.com/EYHN/hexo-helper-live2d
## Live2Dçœ‹æ¿å¨˜
live2d:
  enable: true
  pluginModelPath: assets/
  model:
    #æ¨¡æ¿ç›®å½•ï¼Œåœ¨node_modulesé‡Œ
    use: live2d-widget-model-shizuku  
  display:
    position: left
    width: 300 
    height: 600
  mobile:
    # åœ¨æ‰‹æœºç«¯æ˜¾ç¤º
    show: false   
  rect:
    opacity:0.7



# Local search æœç´¢
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1


#è¯„è®ºç³»ç»Ÿ
valine: true
v_appId: OWbP4V9XAS1W0cOBkvYyuAIz-gzGzoHsz
v_appKey: TyFb4EOA6yox4atRLJpH0MHe
 
# æ˜¯å¦å¼€å¯å­—æ•°ç»Ÿè®¡
#ä¸éœ€è¦ä½¿ç”¨ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
word_count: true

#ç™¾åº¦è‡ªåŠ¨æ¨é€
baidu_push: true
